#! usr/bin/bash
# This bash script is for git automation
REPOS='pwd'
IFS=$'\n'
for REPO in 'ls "$REPOS/"'
do
  if [ -d "$REPOS/$REPO" ]
  then
    echo "Updating $REPOS/$REPO at 'date'"
    if [ -d "$REPOS/$REPO/.git" ]
    then
      cd "$REPOS/$REPO"
      git status
      echo "Fetching..."
      git fetch
      echo "Pulling"
      git pull
    else
      echo "Skipping because it doesn't look like it has a .git folder."
    fi
    echo "Done at 'date'"
    echo
  fi
done
